name: 'Analytics'
version: '2.0'
profile: 'customer_pipeline'
model-paths: ["models"]
seed-paths: ["seeds"]
models:
  Analytics:
    bronze:
      materialized: view
    silver:
      materialized: view
    gold:
      materialized: table