customer_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: RAXXHKB-RZ34633
      user: SAMG
      password: Teranet123frontstreetwest
      role: ACCOUNTADMIN
      database: TRAINING
      warehouse: COMPUTE_WH
      schema: BRONZE
      authenticator: snowflake
