customer_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: RAXXHKB-RZ34633
      user: SAMG
      password: learningAzure2024
      role: ACCOUNTADMIN
      database: TRAINING
      warehouse: COMPUTE_WH
      schema: PUBLIC
      authenticator: snowflake
      threads: 1
