version: 2

sources:
  - name: raw
    database: TRAINING
    schema: BRONZE
    quoting:
      identifier: true
      database: true
      schema: true
    tables:
      - name: RAW_CUSTOMERS
        description: "this table has customers which is getting from salesforce"