version: 2
sources:
  - name: raw
    database: TRAINING
    schema: BRONZE
    tables: 
      - name: RAW_CUSTOMERS
        description: "this table has customers which is getting from salesforce"
        quoting:
          identifier: true